// @vitest-environment jsdom
import React from 'react';
import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createMemoryRouter, RouterProvider } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { LeaseRecord, LocalDatabase, PaymentRecord, TenantRecord } from '../../src/db/database.types';
import { createJsonDbAccountScope, setActiveDatabaseAccount } from '../../src/db/jsonDb';
import { defaultLeaseValues, normalizeLeaseFormData } from '../../src/landlord/leases/schema/leaseFormSchema';
import { defaultPropertyValues } from '../../src/components/property-form/schema';
import { TenantDetailPage } from '../../src/pages/TenantDetailPage';
import { installJsonDbWindow, MemoryStorage, uninstallJsonDbWindow } from '../db/jsonDbStorageHarness';
const A='user-95411',B='user-95412',NOW='2026-09-02T10:00:00.000Z';
const authState=vi.hoisted(()=>({account:{id:'user-95411'} as {id:string}|null}));vi.mock('../../src/auth/AuthContext',()=>({useAuth:()=>({account:authState.account,isInitializing:false})}));
const tenant=(id:string,archived=false,name='Ada'):TenantRecord=>({id,createdAt:NOW,updatedAt:NOW,type:'person',photo:null,avatarColor:'#123456',title:'Mr',firstName:name,middleName:'',lastName:'Tenant',birthDate:'',birthPlace:'',nationality:'IT',fiscalCode:`CF-${name}`,vatNumberPersonal:'',profession:'',monthlyIncome:null,idType:'',idNumber:'',idExpiry:'',identityDocumentFile:null,identityDocumentBackFile:null,companyName:'',companyFiscalCode:'',vatNumber:'',siret:'',capital:'',companyDescription:'',companyRegistryFile:null,email:`${id}@test.it`,emailSecondary:'',mobilePhone:'',phone:'',address1:'',address2:'',city:'',zip:'',state:'',country:'IT',proEmployer:'',proAddress:'',proCity:'',proZip:'',proState:'',proCountry:'',proPhone:'',bankName:'',bankAddress:'',bankCity:'',bankZip:'',bankCountry:'',bankIBAN:'',bankSwiftBic:'',leaveAddress:'',notes:'',status:'attivo',archived,leaseIds:[],guarantors:[],emergencyContacts:[],documents:[],invitation:{status:'not_sent',email:`${id}@test.it`,sentAt:null,acceptedAt:null}});
const db=(tenants:TenantRecord[],leases:LeaseRecord[]=[],payments:PaymentRecord[]=[]):LocalDatabase=>({meta:{schemaVersion:4,seedVersion:1,createdAt:NOW,updatedAt:NOW,source:'seed'},properties:(leases.length||payments.length)?[{id:'p',archived:false,createdAt:NOW,updatedAt:NOW,formData:{...defaultPropertyValues,PropertyTitle:'Test',PropertyAddress:'Via Test',PropertyCity:'Roma',PropertyPostalCode:'00100',PropertyCountry:'IT'},relations:{buildingId:null,tenantIds:tenants.map(t=>t.id),leaseIds:leases.map(l=>l.id)},notes:[],activities:[]}]:[],buildings:[],tenants,leases,payments,contacts:[],documents:[],reservations:[],catalogs:[],inventory:[],maintenance:[],tasks:[],notes:[],messages:[],candidates:[],settings:{},userProfile:{},drafts:[]});
const lease=(tenantId:string):LeaseRecord=>{const f=normalizeLeaseFormData({...defaultLeaseValues,LeaseIdentificativo:'l',PropertyID:'p',LeaseType:'abitativo',LeaseTenantIds:[tenantId],LeaseStartDate:'2025-01-01',LeaseEndDate:'2025-12-31',LeaseBillingPeriod:'monthly'});return{id:'l',propertyId:'p',tenantIds:[tenantId],guarantorIds:[],leaseType:'abitativo',leaseTypeLabel:'Abitativo',startDate:'2025-01-01',endDate:'2025-12-31',status:'terminata',rentAmount:0,utilitiesAmount:0,depositAmount:0,billingPeriod:'monthly',formData:f,archived:true,createdAt:NOW,updatedAt:NOW,notes:'',activity:[],signatureProcess:null,termination:null,financialState:{depositPaymentId:null,depositReturnPaymentId:null,prepaidAppliedAmount:0,prepaidAllocations:[]}}};
const payment=(tenantId:string):PaymentRecord=>({id:'pay',propertyId:'p',leaseId:null,tenantId,type:'rent',category:'manual',amount:1,dueDate:'2025-01-01',paidDate:null,status:'paid',description:'Storico',source:'manual',accountingRole:'income',notes:'',receiptNumber:null,confirmation:null,createdAt:NOW,updatedAt:NOW});
function install(a:LocalDatabase,b=db([])){const s=new MemoryStorage({[`props24.localDb.${A}`]:JSON.stringify(a),[`props24.localDb.${B}`]:JSON.stringify(b)});const w=window;installJsonDbWindow(s);Object.defineProperty(w,'localStorage',{configurable:true,value:s});Object.defineProperty(globalThis,'window',{configurable:true,writable:true,value:w});setActiveDatabaseAccount(A);return s;}
function mount(id='shared'){const router=createMemoryRouter([{path:'/tenants/:id',element:<TenantDetailPage/>},{path:'/tenants/:id/edit',element:<h1>Edit marker</h1>},{path:'/tenants',element:<h1>List marker</h1>}],{initialEntries:[`/tenants/${id}`]});const view=render(<RouterProvider router={router}/>);return{router,...view};}
const stored=(account=A,id='shared')=>createJsonDbAccountScope(account).getDatabase().tenants.find(t=>t.id===id)??null;
async function menuAction(name:string){await userEvent.click(await screen.findByRole('button',{name:'Azioni'}));await userEvent.click(screen.getByRole(name==='Modifica'?'link':'button',{name}));}
async function confirm(label:string){await userEvent.click(screen.getByRole('button',{name:label}));}
afterEach(()=>{cleanup();setActiveDatabaseAccount(null);uninstallJsonDbWindow();authState.account={id:A};vi.clearAllMocks();});
describe('C5.4 lifecycle reale TenantDetailPage',()=>{
 it('active mostra azioni e Modifica naviga',async()=>{install(db([tenant('shared')]));const{router}=mount();expect(screen.queryByText('Archiviato')).toBeNull();await userEvent.click(await screen.findByRole('button',{name:'Azioni'}));expect(screen.getByRole('link',{name:'Modifica'})).toBeTruthy();expect(screen.getByRole('button',{name:'Archivia'})).toBeTruthy();expect(screen.getByRole('button',{name:'Elimina'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Ripristina'})).toBeNull();await userEvent.click(screen.getByRole('link',{name:'Modifica'}));expect(router.state.location.pathname).toBe('/tenants/shared/edit');});
 it('annulla zero mutation poi archivia con badge e route invariata',async()=>{install(db([tenant('shared')]));const{router}=mount();await menuAction('Archivia');await confirm('Annulla');expect(stored()?.archived).toBe(false);expect(screen.queryByText('Operazione completata')).toBeNull();await menuAction('Archivia');await confirm('Archivia inquilino');await waitFor(()=>expect(stored()?.archived).toBe(true));expect(router.state.location.pathname).toBe('/tenants/shared');expect(await screen.findByText('Archiviato')).toBeTruthy();await userEvent.click(screen.getByRole('button',{name:'Azioni'}));expect(screen.getByRole('button',{name:'Ripristina'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Archivia'})).toBeNull();});
 it('remount conserva archive e restore persiste',async()=>{install(db([tenant('shared',true)]));const first=mount();expect(await screen.findByText('Archiviato')).toBeTruthy();first.unmount();mount();expect(await screen.findByText('Archiviato')).toBeTruthy();await menuAction('Ripristina');await confirm('Ripristina inquilino');await waitFor(()=>expect(stored()?.archived).toBe(false));expect(screen.queryByText('Archiviato')).toBeNull();});
 it('delete libero rimuove DB e naviga REPLACE',async()=>{install(db([tenant('shared')]));const{router}=mount();await menuAction('Elimina');await confirm('Elimina inquilino');await waitFor(()=>expect(router.state.location.pathname).toBe('/tenants'));expect(router.state.historyAction).toBe('REPLACE');expect(stored()).toBeNull();expect(screen.getByText('List marker')).toBeTruthy();});
 it.each(['lease','payment'] as const)('delete %s blocked conserva DB route modal e nessun successo',async(kind)=>{const target={...tenant('shared'),leaseIds:kind==='lease'?['l']:[]};install(db([target],kind==='lease'?[lease('shared')]:[],kind==='payment'?[payment('shared')]:[]));const{router}=mount();await menuAction('Elimina');await confirm('Elimina inquilino');expect(await screen.findByRole('alert')).toBeTruthy();expect(stored()).not.toBeNull();expect(router.state.location.pathname).toBe('/tenants/shared');expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.queryByText('Operazione completata')).toBeNull();});
 it('archived libero si elimina senza restore con REPLACE',async()=>{install(db([tenant('shared',true)]));const{router}=mount();expect(await screen.findByText('Archiviato')).toBeTruthy();await menuAction('Elimina');await confirm('Elimina inquilino');await waitFor(()=>expect(router.state.location.pathname).toBe('/tenants'));expect(router.state.historyAction).toBe('REPLACE');expect(stored()).toBeNull();});
 it('account isolation same ID mantiene B identico',async()=>{const ta=tenant('shared'),tb=tenant('shared',false,'Grace'),key=`props24.localDb.${B}`;const storage=install(db([ta]),db([tb]));const original=storage.getItem(key);mount();await menuAction('Archivia');await confirm('Archivia inquilino');await waitFor(()=>expect(stored()?.archived).toBe(true));expect(storage.getItem(key)).toBe(original);});
 it('account assente non muta e mantiene modal',async()=>{install(db([tenant('shared')]));authState.account=null;mount();await menuAction('Archivia');await confirm('Archivia inquilino');expect(await screen.findByText(/Database locale non disponibile/)).toBeTruthy();expect(stored()?.archived).toBe(false);expect(screen.getByRole('dialog')).toBeTruthy();});
});
