// @vitest-environment jsdom
import React from 'react';
import { cleanup, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createMemoryRouter, RouterProvider } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { LeaseRecord, LocalDatabase, PaymentRecord, TenantRecord } from '../../src/db/database.types';
import { createJsonDbAccountScope, setActiveDatabaseAccount } from '../../src/db/jsonDb';
import { defaultLeaseValues, normalizeLeaseFormData } from '../../src/landlord/leases/schema/leaseFormSchema';
import { TenantsPage } from '../../src/pages/TenantsPage';
import { defaultPropertyValues } from '../../src/components/property-form/schema';
import { installJsonDbWindow, MemoryStorage, uninstallJsonDbWindow } from '../db/jsonDbStorageHarness';

const ACCOUNT_A='user-95401', ACCOUNT_B='user-95402', NOW='2026-09-02T10:00:00.000Z';
const authState=vi.hoisted(()=>({account:{id:'user-95401'} as {id:string}|null}));
vi.mock('../../src/auth/AuthContext',()=>({useAuth:()=>({account:authState.account,isInitializing:false})}));
vi.stubGlobal('ResizeObserver',class{observe(){} unobserve(){} disconnect(){}});
const tenant=(id:string,archived=false):TenantRecord=>({id,createdAt:NOW,updatedAt:NOW,type:'person',photo:null,avatarColor:'#123456',title:'Mr',firstName:`Nome ${id}`,middleName:'',lastName:'Tenant',birthDate:'',birthPlace:'',nationality:'IT',fiscalCode:`CF-${id}`,vatNumberPersonal:'',profession:'',monthlyIncome:null,idType:'',idNumber:'',idExpiry:'',identityDocumentFile:null,identityDocumentBackFile:null,companyName:'',companyFiscalCode:'',vatNumber:'',siret:'',capital:'',companyDescription:'',companyRegistryFile:null,email:`${id}@test.it`,emailSecondary:'',mobilePhone:'',phone:'',address1:'',address2:'',city:'',zip:'',state:'',country:'IT',proEmployer:'',proAddress:'',proCity:'',proZip:'',proState:'',proCountry:'',proPhone:'',bankName:'',bankAddress:'',bankCity:'',bankZip:'',bankCountry:'',bankIBAN:'',bankSwiftBic:'',leaveAddress:'',notes:'',status:'attivo',archived,leaseIds:id==='blocked'?['l']:[],guarantors:[],emergencyContacts:[],documents:[],invitation:{status:'not_sent',email:`${id}@test.it`,sentAt:null,acceptedAt:null}});
const db=(tenants:TenantRecord[],leases:LeaseRecord[]=[],payments:PaymentRecord[]=[]):LocalDatabase=>({meta:{schemaVersion:4,seedVersion:1,createdAt:NOW,updatedAt:NOW,source:'seed'},properties:(leases.length||payments.length)?[{id:'property-x',archived:false,createdAt:NOW,updatedAt:NOW,formData:{...defaultPropertyValues,PropertyTitle:'Test',PropertyAddress:'Via Test',PropertyCity:'Roma',PropertyPostalCode:'00100',PropertyCountry:'IT'},relations:{buildingId:null,tenantIds:tenants.map(t=>t.id),leaseIds:leases.map(l=>l.id)},notes:[],activities:[]}]:[],buildings:[],tenants,leases,payments,contacts:[],documents:[],reservations:[],catalogs:[],inventory:[],maintenance:[],tasks:[],notes:[],messages:[],candidates:[],settings:{},userProfile:{},drafts:[]});
const lease=(id:string,tenantId:string):LeaseRecord=>{const formData=normalizeLeaseFormData({...defaultLeaseValues,LeaseIdentificativo:id,PropertyID:'property-x',LeaseType:'abitativo',LeaseTenantIds:[tenantId],LeaseStartDate:'2025-01-01',LeaseEndDate:'2025-12-31',LeaseBillingPeriod:'monthly'});return{id,propertyId:'property-x',tenantIds:[tenantId],guarantorIds:[],leaseType:'abitativo',leaseTypeLabel:'Abitativo',startDate:'2025-01-01',endDate:'2025-12-31',status:'terminata',rentAmount:0,utilitiesAmount:0,depositAmount:0,billingPeriod:'monthly',formData,archived:true,createdAt:NOW,updatedAt:NOW,notes:'',activity:[],signatureProcess:null,termination:null,financialState:{depositPaymentId:null,depositReturnPaymentId:null,prepaidAppliedAmount:0,prepaidAllocations:[]}}};
const payment=(id:string,tenantId:string):PaymentRecord=>({id,propertyId:'property-x',leaseId:null,tenantId,type:'rent',category:'manual',amount:1,dueDate:'2025-01-01',paidDate:null,status:'paid',description:'Storico',source:'manual',accountingRole:'income',notes:'',receiptNumber:null,confirmation:null,createdAt:NOW,updatedAt:NOW});
let storage:MemoryStorage;
function install(a:LocalDatabase,b=db([])){storage=new MemoryStorage({[`props24.localDb.${ACCOUNT_A}`]:JSON.stringify(a),[`props24.localDb.${ACCOUNT_B}`]:JSON.stringify(b)});const w=window;installJsonDbWindow(storage);Object.defineProperty(w,'localStorage',{configurable:true,value:storage});Object.defineProperty(globalThis,'window',{configurable:true,writable:true,value:w});setActiveDatabaseAccount(ACCOUNT_A);}
function mount(){const router=createMemoryRouter([{path:'/tenants',element:<TenantsPage/>},{path:'/tenants/:id',element:<h1>Detail marker</h1>},{path:'/tenants/:id/edit',element:<h1>Edit marker</h1>},{path:'/tenants/new',element:<h1>New marker</h1>}],{initialEntries:['/tenants']});const view=render(<RouterProvider router={router}/>);return{router,...view};}
const stored=(id:string,account=ACCOUNT_A)=>createJsonDbAccountScope(account).getDatabase().tenants.find(t=>t.id===id)??null;
async function row(id:string){return (await screen.findByText(`Nome ${id} Tenant`)).closest('tr') as HTMLTableRowElement;}
async function action(id:string,name:string){await userEvent.click(within(await row(id)).getByRole('button',{name:/Azioni per/}));await userEvent.click(await screen.findByRole('menuitem',{name}));}
async function confirm(label:string){await userEvent.click(screen.getByRole('button',{name:label}));}
afterEach(()=>{cleanup();setActiveDatabaseAccount(null);uninstallJsonDbWindow();authState.account={id:ACCOUNT_A};vi.clearAllMocks();});

describe('C5.4 lifecycle reale TenantsPage',()=>{
 it('menu active e modifica navigano realmente',async()=>{install(db([tenant('a')]));const{router}=mount();await userEvent.click(within(await row('a')).getByRole('button',{name:/Azioni/}));expect(screen.getByRole('menuitem',{name:'Modifica'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'Archivia'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'Elimina'})).toBeTruthy();expect(screen.queryByRole('menuitem',{name:'Ripristina'})).toBeNull();await userEvent.click(screen.getByRole('menuitem',{name:'Modifica'}));expect(router.state.location.pathname).toBe('/tenants/a/edit');});
 it('annulla poi archivia e persiste dopo remount',async()=>{install(db([tenant('a')]));const first=mount();await action('a','Archivia');await confirm('Annulla');expect(stored('a')?.archived).toBe(false);await action('a','Archivia');await confirm('Archivia inquilino');await waitFor(()=>expect(stored('a')?.archived).toBe(true));expect(screen.getByRole('status').textContent).toMatch(/Operazione completata/);first.unmount();mount();await userEvent.click(screen.getByRole('button',{name:'Archivio'}));expect(await row('a')).toBeTruthy();});
 it('menu archived e restore persistito',async()=>{install(db([tenant('a',true)]));mount();await userEvent.click(screen.getByRole('button',{name:'Archivio'}));await userEvent.click(within(await row('a')).getByRole('button',{name:/Azioni/}));expect(screen.getByRole('menuitem',{name:'Modifica'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'Ripristina'})).toBeTruthy();expect(screen.getByRole('menuitem',{name:'Elimina'})).toBeTruthy();expect(screen.queryByRole('menuitem',{name:'Archivia'})).toBeNull();await userEvent.click(screen.getByRole('menuitem',{name:'Ripristina'}));await confirm('Ripristina inquilino');await waitFor(()=>expect(stored('a')?.archived).toBe(false));expect(screen.queryByText('Nome a Tenant')).toBeNull();await userEvent.click(screen.getByRole('button',{name:'Attivi'}));expect(await row('a')).toBeTruthy();});
 it('single delete libero rimuove DB e chiude modal',async()=>{install(db([tenant('a')]));mount();await action('a','Elimina');await confirm('Elimina inquilino');await waitFor(()=>expect(stored('a')).toBeNull());expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByRole('status')).toBeTruthy();});
 it.each([['archive',false,'Archivia','Archivia inquilini'],['restore',true,'Ripristina','Ripristina inquilini'],['delete',false,'Elimina','Elimina inquilini']] as const)('bulk %s persiste atomicamente',async(op,archived,label,confirmLabel)=>{install(db([tenant('a',archived),tenant('b',archived),tenant('c',archived)]));mount();if(archived)await userEvent.click(screen.getByRole('button',{name:'Archivio'}));await userEvent.click(within(await row('a')).getByRole('checkbox'));await userEvent.click(within(await row('b')).getByRole('checkbox'));await userEvent.click(screen.getByRole('button',{name:label}));await confirm(confirmLabel);await waitFor(()=>{if(op==='delete'){expect(stored('a')).toBeNull();expect(stored('b')).toBeNull();}else{expect(stored('a')?.archived).toBe(op==='archive');expect(stored('b')?.archived).toBe(op==='archive');}});expect(stored('c')).not.toBeNull();expect(screen.queryByRole('dialog')).toBeNull();});
 it.each(['lease','payment'] as const)('bulk delete %s blocker resta atomico e conserva UI',async(kind)=>{const free=tenant('free'),blocked=tenant('blocked');install(db([free,blocked],kind==='lease'?[lease('l',blocked.id)]:[],kind==='payment'?[payment('p',blocked.id)]:[]));mount();await userEvent.click(within(await row('free')).getByRole('checkbox'));await userEvent.click(within(await row('blocked')).getByRole('checkbox'));await userEvent.click(screen.getByRole('button',{name:'Elimina'}));await confirm('Elimina inquilini');expect(await screen.findByRole('alert')).toBeTruthy();expect(stored('free')).not.toBeNull();expect(stored('blocked')).not.toBeNull();expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.getAllByRole('checkbox').filter(x=>(x as HTMLInputElement).checked)).toHaveLength(3);expect(screen.queryByText('Operazione completata')).toBeNull();});
 it('tab e ricerca puliscono selection',async()=>{install(db([tenant('a')]));mount();await userEvent.click(within(await row('a')).getByRole('checkbox'));await userEvent.click(screen.getByRole('button',{name:'Archivio'}));await userEvent.click(screen.getByRole('button',{name:'Attivi'}));const current=within(await row('a')).getByRole('checkbox') as HTMLInputElement;expect(current.checked).toBe(false);await userEvent.click(current);const search=screen.getByPlaceholderText(/Cerca/i);await userEvent.type(search,'x');await userEvent.clear(search);expect((within(await row('a')).getByRole('checkbox') as HTMLInputElement).checked).toBe(false);});
 it('filtro proprieta pulisce selection',async()=>{const target={...tenant('a'),leaseIds:['l']};install(db([target],[lease('l','a')]));mount();await userEvent.click(within(await row('a')).getByRole('checkbox'));const propertyFilter=document.querySelector('#search_PropertyID') as HTMLSelectElement;await userEvent.selectOptions(propertyFilter,'property-x');await userEvent.selectOptions(propertyFilter,'');expect((within(await row('a')).getByRole('checkbox') as HTMLInputElement).checked).toBe(false);});
 it('account assente mantiene modal e DB invariato',async()=>{install(db([tenant('a')]));authState.account=null;mount();await action('a','Archivia');await confirm('Archivia inquilino');expect(await screen.findByText(/Database locale non disponibile/)).toBeTruthy();expect(stored('a')?.archived).toBe(false);expect(screen.getByRole('dialog')).toBeTruthy();});
 it('azioni C6 restano pending',async()=>{install(db([tenant('a')]));mount();await userEvent.click(within(await row('a')).getByRole('button',{name:/Azioni/}));for(const name of ['Invia un messaggio','Crea un affitto','Appuntamento','Saldo locatario','Finanze'])expect(screen.getByRole('menuitem',{name}).getAttribute('aria-disabled')).toBe('true');});
});
