import type { TenantRecord } from '../../db/database.types';
import { normalizeTenantDraft, type TenantFormData } from './schema';

export function tenantRecordToFormData(record: TenantRecord): TenantFormData {
    return normalizeTenantDraft(structuredClone({
        TenantType: record.type,
        TenantPhoto: record.photo,
        TenantAvatarHexColor: record.avatarColor,
        TenantTitle: record.title,
        TenantFirstName: record.firstName,
        TenantMiddleName: record.middleName,
        TenantLastName: record.lastName,
        TenantBirthDate: record.birthDate,
        TenantBirthPlace: record.birthPlace,
        TenantNationality: record.nationality,
        TenantFiscalCode: record.fiscalCode,
        TenantVatNumberPersonal: record.vatNumberPersonal,
        TenantProfession: record.profession,
        TenantRevenus: record.monthlyIncome,
        TenantIDType: record.idType,
        TenantIDNumber: record.idNumber,
        TenantIDExpiry: record.idExpiry,
        TenantIDCard: record.identityDocumentFile,
        TenantIDCardBack: record.identityDocumentBackFile,
        TenantCompanyName: record.companyName,
        TenantCompanyFiscalCode: record.companyFiscalCode,
        TenantVatNumber: record.vatNumber,
        TenantSiret: record.siret,
        TenantCapital: record.capital,
        TenantCompanyDescription: record.companyDescription,
        TenantCompanyRegistryFile: record.companyRegistryFile,
        TenantEmail: record.email,
        TenantEmailSecond: record.emailSecondary,
        TenantMobilePhoneNat: record.mobilePhone,
        TenantPhoneNat: record.phone,
        TenantAddress1: record.address1,
        TenantAddress2: record.address2,
        TenantCity: record.city,
        TenantZip: record.zip,
        TenantState: record.state,
        TenantCountry: record.country,
        TenantProEmployer: record.proEmployer,
        TenantProAddress: record.proAddress,
        TenantProCity: record.proCity,
        TenantProZip: record.proZip,
        TenantProState: record.proState,
        TenantProCountry: record.proCountry,
        TenantProPhoneNat: record.proPhone,
        TenantBankName: record.bankName,
        TenantBankAddress: record.bankAddress,
        TenantBankCity: record.bankCity,
        TenantBankZip: record.bankZip,
        TenantBankCountry: record.bankCountry,
        TenantBankIBAN: record.bankIBAN,
        TenantBankSwiftBic: record.bankSwiftBic,
        TenantLeaveAddress: record.leaveAddress,
        TenantNotes: record.notes,
        TenantGuarantors: record.guarantors,
        TenantEmergencyContacts: record.emergencyContacts,
        TenantDocuments: record.documents,
    }));
}
